---
title: "Solo Project"
format: html
---

```{r}
# Import needed packages
library(sf)
library(tidyverse)
library(rnaturalearth)
```

```{r}
# Load in the data
ufo_spottings <- read_csv("../data/ufo_spottings.csv")
canada_shape = ne_states(country = "canada")
```

```{r}
# Test shape file 
ggplot() +
  geom_sf(data = canada_shape)
```

```{r}
# Clean data 

ufo_spottings_ca <- ufo_spottings |>
  filter(country == "ca") |>
  select(state) |>
  group_by(state) |>
  summarise(count = n())

head(ufo_spottings_ca)

shape_data <- canada_shape |>
  select(name, geometry)

head(shape_data)
```

```{r}
# Join Data 

cleaned_ufo <- ufo_spottings_ca |>
  mutate(state = case_when(
    state == "pq" ~ "qc",
    state == "sa" ~ "sk",
    TRUE ~ state)) |>
  mutate(state = case_when(
    state == "ab" ~ "Alberta",
    state == "bc" ~ "British Columbia",
    state == "mb" ~ "Manitoba",
    state == "nb" ~ "New Brunswick",
    state == "nf" ~ "Newfoundland and Labrador",
    state == "ns" ~ "Nova Scotia",
    state == "nt" ~ "Northwest Territories",
    state == "on" ~ "Ontario",
    state == "pe" ~ "Prince Edward Island",
    state == "qc" ~ "Québec",
    state == "sk" ~ "Saskatchewan",
    state == "yt" ~ "Yukon",
    state == "yk" ~ "Nunavut",
    TRUE ~ state  
  ))


unified_data <- shape_data |> 
  left_join(cleaned_ufo, join_by(name == state)) |>
  filter(!is.na(count))
```

```{r}
#|fig-cap: "UFO Sightings in CA over the last century - Data from National UFO Reporting Center, made by Julia Prewitt"
#|fig-alt: "Choropleth map of Canada's provinces and territories illustrating UFO Sightings in CA over the last century. Provinces further north have few sightings in comparison to more southern provinces. "

# Make plot of UFO sightings in Canadian Provinces & Territories
ggplot(unified_data) +
  geom_sf(aes(fill = count)) +
  scale_fill_viridis_c(option = "plasma") +
  labs(title = "UFO Sightings in Canada Over the Last Century",
       fill = "Sightings") +
  theme_minimal()

```

We can see that there are more UFO sightings in more populated areas; this visualization is a good starting point for understanding how UFO sighting increase with people being present, and future investigation can and should examine UFO sightings per captia to understand if certain regions are more likely than others to experience UFO sightings. 
